### ISSUE TITLE
How should I refresh tokens?

### ISSUE THREAD

**Issue by dancodes** [antihax/goesi#8]
I've successfully set up a small application that fetches EVE mails, the easy to read methods are useful, so great job.

When I authenticate with SSO, I get an access token and a refresh token, both which I then store. However, when I try to do an ESI call after more than 1200 seconds, I get an `{"error": "expired", "sso_status": 400}` response.

Wasn't the library supposed to automatically refresh this token? If not, how should I proceed?

Thanks!

**Comment by antihax** [comment]
Can you post some code? Tokensource should refresh the token if it expired.

**Comment by dancodes** [comment]
My mistake: I was manually creating the oauth2.Token objects and did not set an Expiry attribute to them. Closing this. 

Great library btw, thanks a lot!
